### PR TITLE
Reduce appends when zero rate model is used

### PR DESCRIPTION
**Pull request by zmertens**
#8

### CODE REVIEW

**Comment by reedacartwright** [comment]
Can you explain this a bit more?

**Comment by zmertens** [comment]
I was aiming to reduce the number of append calls during alignment when the rate model is zero. Take the `basic-dna-zero` example file, for instance, a set of alignments could look like:

```
 Dawg      TAGACCCGTCAAGTGTTCAAACAGCCCATAGTGCCATCTAATATCTAACAGATTCATTAT
 Man        TAGACCCGTCAAGTGTTCAAACAGCCCATAGTGCCATCTAATATCTAACAGATTCATTAT
 Monkey  TAGACCCGTCAAGTGTTCAAACAGCCCATAGTGCCATCTAATATCTAACAGATTCATTAT
```

If we just align one set and append the residual to the string and then just copy over the other strings it could significantly reduce the number of append calls. I did the analysis using `valgrind/callgrind`

**Comment by reedacartwright** [comment]
Does this work with indels?

**Comment by zmertens** [comment]
I think it does, the only changes should be after the indels have already gone through the evolution.

**Comment by reedacartwright** [comment]
I don't think this change properly aligns indels.

**Pull request closed without merging**
