### PR TITLE
Add C++11 standard to CMake

### PR DESCRIPTION
**Pull request by zmertens**
#16

### CODE REVIEW

**Comment by reedacartwright** [comment]
Jenkins, okay to test

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by reedacartwright** [comment]
Jenkins, retest this please

**Comment by reedacartwright** [comment]
@zryan3 There is a compiling problem with this patch and GCC 4.8.2.

**Comment by zmertens** [comment]
Updated the `seg::iterator` to no longer be const

**Pull request merged**
